kind = "web"
previewPath = "/"
title = "NetPlay"
version = "1.0.0"
id = "artifacts/netplay"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25512

[services.development]
run = "pnpm --filter @workspace/netplay run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/netplay", "run", "build" ]
publicDir = "artifacts/netplay/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25512"
BASE_PATH = "/"
