import { Router } from "express";
import healthRouter from "./health";
import teraboxRouter from "./terabox";
import teraboxV2Router from "./terabox-v2";
import teraboxV3Router from "./terabox-v3";
import proxyStreamRouter from "./proxy-stream";
import keepwarmRouter from "./keepwarm";
import probeStreamsRouter from "./probe-streams";
import tmdbRouter from "./tmdb";
import aiRouter from "./ai";
import betterflixRouter from "./betterflix";
import vidsrcRouter from "./vidsrc";
import flix3Router from "./flix3";
import moviesRouter from "./movies";
import syncRouter from "./sync";
import settingsRouter from "./settings";
import contentTrackerRouter from "./content-tracker";
import adminDuplicatesRouter from "./admin-duplicates";
import mysqlRouter from "./mysql";
import mysqlAuthRouter from "./mysql-auth";

const router = Router();

router.use(healthRouter);
router.use(teraboxRouter);
router.use(teraboxV2Router);
router.use(teraboxV3Router);
router.use(proxyStreamRouter);
router.use(keepwarmRouter);
router.use(probeStreamsRouter);
router.use(tmdbRouter);
router.use(aiRouter);
router.use(betterflixRouter);
router.use(vidsrcRouter);
router.use(flix3Router);
router.use(moviesRouter);
router.use(syncRouter);
router.use(settingsRouter);
router.use(contentTrackerRouter);
router.use(adminDuplicatesRouter);
router.use(mysqlRouter);
router.use(mysqlAuthRouter);

export default router;
