// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/em-alta/EmAlta.tsx": () => import("../components/mockups/em-alta/EmAlta.tsx"),
  "./components/mockups/netplay/Detail.tsx": () => import("../components/mockups/netplay/Detail.tsx"),
  "./components/mockups/netplay/Home.tsx": () => import("../components/mockups/netplay/Home.tsx")
};
